config/routes.rb
Rails.application.routes.draw do
  # Root
  root to: 'categories#index'
  # Devise
  devise_for :providers
  devise_for :customers

  # Resources
  resources :categories
  resources :customers
  resources :providers
  resources :social_networks
  resources :services
  resources :appointments

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :customer
  belongs_to :provider
  belongs_to :service
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :services, dependent: :destroy
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :appointments, dependent: :destroy
  has_many :providers, through: :appointments
end

app/models/provider.rb
class Provider < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :appointments, dependent: :destroy
  has_many :customers, through: :appointments

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/service.rb
class Service < ApplicationRecord
  has_many_attached :photos
  belongs_to :category
  belongs_to :provider
  has_many :social_networks, dependent: :destroy
  has_many :appointments, dependent: :destroy
  # Geocoded
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/social_network.rb
class SocialNetwork < ApplicationRecord
  belongs_to :service
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name dni address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name address])

  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[new show create edit update destroy]
  
  def index
    @appointment = Appointment.all
  end

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)
    if @appointment.save
      redirect_to appointment_path(@appointment)
    else
      render :new
    end
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  def edit
  end

  def update
    if @appointment.update(appointment_params)
      redirect_to appointment_path(@appointment)
    else
      render :edit
    end
  end

  def destroy
    if @appointment.destroy
      redirect_to appointment_path
    else
      render :new
    end
  end

  private

  #def set_user
   # @user = current_user
  # end

  def set_appointment
    @appointment = Appointment.new(params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    if params[:query]
      @categories = Category.where("name LIKE ?", "%#{params[:query]}%")
    else
      @categories = Category.all
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  # def new
  # end

  # def create
  #   @categories = categories.new(categories_params)
  #   @categories.user = @user
  #   authorize @categories
  #   if @categories.save
  #     redirect_to categories_path(@categories)
  #   else
  #     render :new
  #   end
  # end

  # def edit
  # end

  # def update
  #   if @categories.update(categories_params)
  #     redirect_to categories_path(@categories)
  #   else
  #     render :edit
  #   end
  # end

  # def destroy
  #   if @categories.destroy
  #     redirect_to categories_path
  #   else
  #     render :show
  #   end
  # end

  # private

  # def set_user
  #   @user = current_user
  # end

  # def set_categories
  #   @categories = categories.find(params[:id])
  #   authorize @categories
  # end

  # def categories_params
  #   params.require(:service).permit(:name, :description, :price, :photo)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
  end

  def new
    @customer = Customer.new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_user
    @user = current_user
  end

  def set_appointment
    @customer = Customer.find(params[:id])
    authorize @customer
  end

  def customer_params
    params.require(:service).permit(:name, :description, :price, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  def index
  end

  def new
    @provider = Provider.new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_user
    @user = current_user
  end

  def set_provider
    @provider = Provider.find(params[:id])
    # authorize @provider
  end

  def provider_params
    params.require(:service).permit(:name, :description, :price, :photo)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[ show  edit update destroy]
 def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)

    @service.provider = current_provider if current_provider

    if @service.save
      redirect_to services_path
      flash[:notice] = "El servicio #{@service.name} ha sido creado exitosamente."
    else
      flash[:notice] = "El servicio no pudo ser creado."
      render :new
    end
  end

  def index
    @services = Service.all
    @markers = @services.geocoded.map do |service|
      {
        lat: service.latitude,
        lng: service.longitude
      }
    end
  end

  def show
  end
  def edit
  end

  def update
    if @service.update(service_params)
      redirect_to service_path
      flash[:notice] = "El servicio #{@service.name} ha sido actualizado exitosamente."
    else
      render :edit
    end
  end

  def destroy
   @service.destroy
   redirect_to services_path
  end

  private

  def set_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(
      :name,
      :address,
      :city,
      :telephone,
      :description,
      :availability,
      :category_id,
      :latitude,
      :longitude,
      photos: []
    )
  end
end

app/controllers/social_networks_controller.rb
class SocialNetworksController < ApplicationController
  def index
  end
   def new
    @social_network =  social_network.new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_user
    @user = current_user
  end

  def set_appointment
    @social_network = social_network.find(params[:id])
    authorize @social_network
  end

  def social_network_params
    params.require(:service).permit(:name, :description, :price, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/new.html.erb
<h1>nuevas categorias</h1>

app/views/categories/show.html.erb
<div class="container my-3">
  <h1><%= @category.name %></h1>
  <div class="cards">
    <!-- Services -->
    <% @category.services.each do |service| %>
      <div class="card-trip">
        <!-- Carrusel de fotos -->
        <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner style=">
            <% service.photos.each_with_index do |photo, index| %>
              <% if index.zero? %>
                <div class="carousel-item active">
                 <img class="d-block w-100 h-500px" src="<%= cl_image_path photo.key %>" alt="slide 1">
                </div>
              <% else %>
                <div class="carousel-item">
                  <img class="d-block w-100 h-500px" src="<%= cl_image_path photo.key %>" alt="slide <%= index %>">
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="card-trip-infos">
          <div>
            <h2><%= service.name %></h2>
            <p><%= service.description %></p>
            <p><%= service.city %></p>
            <%= link_to "Ir a detalles", service_path(service), class: "btn btn-flat" %>
            <%= link_to "Reservar", new_appointment_path, class: 'btn btn-flat' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
  <!-- footer -->
<div class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-xs-12">
                    <div class="first">
                        <h4>SERVICIOS DE MASCOTAS🐠🐰🐯😹</h4>
                        <p> Nos Comprometemos a Combatir el Maltrato anima!!</p>
                        <p> Servicio de Adopción.</p>
                        <p> Servicios de Rescate.</p>
                        <p> Servicios de Estética y salud medicina complementaria.</p>
                        <p> Servicios de Nutrición y alimentación animal.</p>
                        <p> Servicios de Funeraria y Cementerios(crematorio).</p>
                    </div>
                </div>

                <div class="col-md-4 col-xs-12">
                    <div class="second">
                        <h4> Se parte de esta Gran COMUNIDAD 💜</h4>
                        <ul>
                            <li><%= link_to "Ir a Servicios", services_path, class:'btn btn-'%></li>
                            <li><%= link_to "Crea tu Servicio", services_path, class:'btn btn-'%></li>
                            <li><%= link_to "Categorias", categories_path, class:'btn btn-'%></li>
                            <li><a href="#">"Ingresa con el avatar "youtube" para risas de animales"</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-4 col-xs-12">
                    <div class="third">
                        <h4> Contactanos</h4>
                        <ul>
                            <li>Vanessa Nicol Sagredo Valdivia </li>
                            <li>Alejandro Eric Yévenes Zúñiga</li>


                          <li><i class="far fa-envelope"></i> sagredovanessa619@mascotagram.com</li>
                            <li><i class="far fa-envelope"></i> ayevenes@mascotagram.com</li>


                          <li><i class="fas fa-map-marker-alt"></i> Barrio lastarrias #3048 -Providencia-Santiago de Chile</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="line"></div>
                    <div class="second2">
                        <!--<a href="https://codepen.io/AndreeaBunget" target="_blank"> <i class="fab fa-codepen fa-2x margin"></i></a> -->
                        <a href="https://github.com/features" target="_blank"> <i class="fab fa-github fa-2x margin"></i></a>
                        <a href="https://www.linkedin.com/" target="_blank"> <i class="fab fa-linkedin fa-2x margin"></i></a>
                        <a href="https://www.youtube.com/watch?v=5dDjJLdQ6Jo" target="_blank"><i class="fab fa-youtube fa-2x margin" ></i></a>

                    </div>

                </div>
            </div>
            </div>
    </div>



</body>

app/views/customers/index.html.erb
<!-- Banner -->
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/bad-kuky-0ne/image/upload/v1631635271/pinguino_mz8qkf.jpg);">
  <div class="container">
    <h1>Busca los mejores <strong>servicios de mascotas 🦕🐠🐿🐇🦔</strong></h1>
    <p>Ven a Ser Parte De Esta Gran Comunidad🐇🌍🐺😹.</p>
    <a class="btn btn-flat" href="#">Contáctanos</a>
  </div>
</div>
<div class="container my-3">
  <h1>Categorías</h1>
  <!-- Buscador servicios por categoría -->
  <form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
    <div class="search-form-control form-group">
      <input class="form-control string required" type="text" name="search[query]" id="search_query" />
      <button name="button" type="submit" class="btn btn-flat">
        <i class="fas fa-search"></i>Buscar
      </button>
    </div>
  </form>

app/views/customers/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/customers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mascotagram</title>
    <meta charset='utf-8'>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= render 'shared/carouselExampleIndicators' %>
    <!--<%= render 'shared/footer' %> -->
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Mascota Gram🦕🐠🐿🐇🦔🐄🐘🐢😻🐻🙊🐺😹</h1>

<form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
</form>
</div>
<p>Registrate!! y se parte de esta gran Comunidad🐇🌍🐺😹</p>

app/views/providers/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/providers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/services/index.html.erb
<div class="d-flex justify-content-between align-items-center m-3">
  <h1 class="text-center">  Servicios de Macotas MASCOTAGRAM</h1>
  <%= link_to "+ Crear un servicio", new_service_path, class: "btn btn-flat" %>
</div>
<div class="d-flex justify-content-around mx-3">
  <div class="cards">
    <% @services.each do |service| %>
      <div class="card-trip">
        <!-- Carrusel de fotos -->
        <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <% service.photos.each_with_index do |photo, index| %>
              <% if index.zero? %>
                <div class="carousel-item active">
                 <img class="d-block w-100" src="<%= cl_image_path photo.key %>" alt="slide 1">
                </div>
              <% else %>
                <div class="carousel-item">
                  <img class="d-block w-100" src="<%= cl_image_path photo.key %>" alt="slide <%= index %>">
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="card-trip-infos">
          <div>
            <h2><%= service.name %></h2>
            <p>Descripción: <%= service.description %></p>
            <p>Ciudad: <%= service.city %></p>
            <p>Disponibilidad: <%= service.availability %></p>
            <p>Proveedor: <%= service.provider.full_name %></p>
            <%= link_to "Ir a detalles", service_path(service), class: "btn btn-flat" %>
            <%= link_to "Reservar", new_appointment_path, class: 'btn btn-flat' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div id="map"
    class="mx-2"
    style="width: 50%; height: 600px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>
    <!-- footer -->
<div class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-xs-12">
                    <div class="first">
                        <h4>SERVICIOS DE MASCOTAS🐱🐶🐠🐰🐯😹</h4>
                        <p> Nos Comprometemos a Combatir el Maltrato anima!!</p>
                        <p> Servicio de Adopcion.</p>
                        <p> Servicios de Rescate.</p>
                        <p> Servicios de Estetica y salud medicina complementaria.</p>
                        <p> Servicios de Nutricion y alimentacion animal.</p>
                        <p> Servicios de Funeraria y Cementerios(crematorio).</p>
                    </div>
                </div>

                <div class="col-md-4 col-xs-12">
                    <div class="second">
                        <h4> Se parte de esta Gran COMUNIDAD 💜</h4>
                        <ul>
                            <li><%= link_to "Ir a Servicios", services_path, class:'btn btn-'%></li>
                            <li><%= link_to "Crea tu Servicio", services_path, class:'btn btn-'%></li>
                            <li><%= link_to "Categorias", categories_path, class:'btn btn-'%></li>
                            <li><a href="#">"Ingresa con el avatar "youtube" para risas de animales"</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-4 col-xs-12">
                    <div class="third">
                        <h4> Contactanos</h4>
                        <ul>
                            <li>Vanessa Nicol Sagredo Valdivia </li>
                            <li>Alejandro Eric Yévenes Zúñiga</li>


                          <li><i class="far fa-envelope"></i> sagredovanessa619@mascotagram.com</li>
                            <li><i class="far fa-envelope"></i> ayevenes@mascotagram.com</li>


                          <li><i class="fas fa-map-marker-alt"></i> Barrio lastarrias #3048 -Providencia-Santiago de Chile</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="line"></div>
                    <div class="second2">
                        <!--<a href="https://codepen.io/AndreeaBunget" target="_blank"> <i class="fab fa-codepen fa-2x margin"></i></a> -->
                        <a href="https://github.com/features" target="_blank"> <i class="fab fa-github fa-2x margin"></i></a>
                        <a href="https://www.linkedin.com/" target="_blank"> <i class="fab fa-linkedin fa-2x margin"></i></a>
                        <a href="https://www.youtube.com/watch?v=ODiHIS3AWLg" target="_blank"><i class="fab fa-youtube fa-2x margin" ></i></a>

                    </div>

                </div>
            </div>
            </div>
    </div>



</body>

app/views/services/show.html.erb
<div class="container">
    <div class="card">
    <div class="card-body d-flex">
    <div class="card-body text-center">
        <h2 class="card-title font-weight-bold">Detalle Servicio</h2>
        <div class="imagen-p-5- d-flex" ></div>
    <img src="https://res.cloudinary.com/bad-kuky-0ne/image/upload/v1631508519/large_service_2_gato_jknlvl.png" />
      <!-- <h5 class="card-title">Detalle de servicio</h5> -->
          <!-- <small class="d-flex justify-content-between align-items-text-rigth m-4"><h1><%= @service.name %></h1> -->
             <h2>Dirección: <%= @service.address %></h2>
              <h2>Categoría: <%= @service.category.name %></h2>
              <h2>Ciudad: <%= @service.city %></h2>
              <h2>Horario de atención: <%= @service.availability %></h2></small>
    </div>
</div>
  <!-- Fotos -->
  <div class="card-body">
  <div class="d-flex justify-content-around">
    <% @service.photos.each do |photo| %>
      <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
    <% end %>
  </div>
<br>
<br>
  <!-- Botones -->
    <div class="card">
    <div class="card-body text-center">
  <!-- <div class="d-flex"> -->
    <%= link_to "Volver", services_path, class:'btn btn-flat'%>
    <!-- <%= link_to "Eliminar", services_path, data: { confirm: "¿Estás seguro de eliminar #{@service.name}?"}, class: 'btn btn-secondary' %> -->
    <%= link_to "Editar", edit_service_path, class: 'btn btn-ghost' %>
    <%= link_to "Reservar", new_appointment_path, class: 'btn btn-flat' %>
  </div>
</div>
    <!-- footer -->
<div class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-xs-12">
                    <div class="first">
                        <h4>SERVICIOS DE MASCOTAS🐱🐶🐰😹</h4>
                        <p> Nos Comprometemos a Combatir el Maltrato anima!!</p>
                        <p> Servicio de Adopcion.</p>
                        <p> Servicios de Rescate.</p>
                        <p> Servicios de Estetica y salud medicina complementaria.</p>
                        <p> Servicios de Nutricion y alimentacion animal.</p>
                        <p> Servicios de Funeraria y Cementerios(crematorio).</p>
                    </div>
                </div>

                <div class="col-md-4 col-xs-12">
                    <div class="second">
                        <h4> Se parte de esta Gran COMUNIDAD 💜</h4>
                        <ul>
                            <li><%= link_to "Ir a Servicios", services_path, class:'btn btn-'%></li>
                            <li><%= link_to "Crea tu Servicio", services_path, class:'btn btn-'%></li>
                            <li><%= link_to "Categorias", categories_path, class:'btn btn-'%></li>
                            <li><a href="#">"Ingresa con el avatar "youtube" para risas de animales"</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-4 col-xs-12">
                    <div class="third">
                        <h4> Contactanos</h4>
                        <ul>
                            <li>Vanessa Nicol Sagredo Valdivia </li>
                            <li>Alejandro Eric Yévenes Zúñiga</li>


                          <li><i class="far fa-envelope"></i> sagredovanessa619@mascotagram.com</li>
                            <li><i class="far fa-envelope"></i> ayevenes@mascotagram.com</li>


                          <li><i class="fas fa-map-marker-alt"></i> Barrio lastarrias #3048 -Providencia-Santiago de Chile</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="line"></div>
                    <div class="second2">
                        <!--<a href="https://codepen.io/AndreeaBunget" target="_blank"> <i class="fab fa-codepen fa-2x margin"></i></a> -->
                        <a href="https://github.com/features" target="_blank"> <i class="fab fa-github fa-2x margin"></i></a>
                        <a href="https://www.linkedin.com/" target="_blank"> <i class="fab fa-linkedin fa-2x margin"></i></a>
                        <a href="https://www.youtube.com/watch?v=WwMchL5_z7g" target="_blank"><i class="fab fa-youtube fa-2x margin" ></i></a>

                    </div>

                </div>
            </div>
            </div>
    </div>



</body>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <% if customer_signed_in?  %>
      <span><%= current_customer.email %> | Customer </span>
    <% elsif provider_signed_in? %>
       <span><%= current_provider.email %> | Provider </span>
    <% end %>
    <%= image_tag "logo.png" %>
    <!--<%= link_to "Servicios", services_path, class:'btn btn-flat'%> -->
    <%= link_to "Categorias", categories_path, class: 'btn btn-flat' %>
    <%= link_to "Descubre los mejores servicios para tu mascotas", services_path, class: 'btn btn-flat' %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if customer_signed_in? || provider_signed_in? %>
        <li class="nav-item active">
         <!-- <%= link_to "Categorias", "categories", class: "nav-link" %> -->
        </li>
        <li class="nav-item">
          <!-- <%= link_to "Servicio", services_path, class: "nav-link" %> -->
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "logo.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <!-- <%= link_to "Categorias", "categories", class: "dropdown-item" %> -->
            <%= link_to "", "#", class: "dropdown-item" %>
            <% if customer_signed_in?  %>
              <%= link_to "Log out", destroy_customer_session_path, method: :delete, class: "dropdown-item" %>
            <% elsif provider_signed_in? %>
              <%= link_to "Log out", destroy_provider_session_path, method: :delete, class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Ingreso cliente", new_customer_session_path, class: "btn btn-flat" %>
        </li>
        <li class="nav-item">
          <%= link_to "Ingreso proveedor", new_provider_session_path, class: "btn btn-flat" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/social_networks/index.html.erb
<h1>mascotass</h1>